# Generated by Django 3.2 on 2021-08-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='open_transactions',
            field=models.TextField(blank=True),
        ),
    ]
