# Generated by Django 3.2.5 on 2021-07-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_user_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='private_key',
            field=models.CharField(max_length=1024),
        ),
    ]
