# Generated by Django 3.2.5 on 2021-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_auto_20210727_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blockchain',
            field=models.TextField(blank=True),
        ),
    ]
